### PR TITLE
Feature/libitd 938

### PR DESCRIPTION
**Pull request by cfitz**
https://issues.umd.edu/browse/LIBITD-938

### CODE REVIEW

**Comment by dsteelma-umd** [comment]
@cfitz - Two things:

1) This pull request has failing unit tests (even on the local development environment):

```
> rake test
Started with run options --seed 3686

ERROR["test_should_allow_authed_users", HomeControllerTest, 17.99354924200452]
 test_should_allow_authed_users#HomeControllerTest (17.99s)
ActionView::Template::Error:         ActionView::Template::Error: uninitialized constant ActionView::CompiledTemplates::FISCAL_YEAR
            app/views/home/index.html.erb:9:in `_app_views_home_index_html_erb___4109284680562374257_70174200583680'
            test/controllers/home_controller_test.rb:13:in `block (2 levels) in <class:HomeControllerTest>'
            test/test_helper.rb:34:in `run_as_user'
            test/controllers/home_controller_test.rb:12:in `block in <class:HomeControllerTest>'

 FAIL["test_should_update_contractor_request", ContractorRequestsControllerTest, 23.97954961800133]
 test_should_update_contractor_request#ContractorRequestsControllerTest (23.98s)
        Expected response to be a <redirect>, but was <200>
        test/controllers/contractor_requests_controller_test.rb:126:in `block in <class:ContractorRequestsControllerTest>'

 FAIL["test_should_create_contractor_request", ContractorRequestsControllerTest, 24.6348548179958]
 test_should_create_contractor_request#ContractorRequestsControllerTest (24.63s)
        "Request.count" didn't change by 1.
        Expected: 219
          Actual: 218
        test/controllers/contractor_requests_controller_test.rb:46:in `block in <class:ContractorRequestsControllerTest>'

 FAIL["test_should_create/update_contractor_request_but_without_admin_only_values_when_not_admin", ContractorRequestsControllerTest, 25.106726231984794]
 test_should_create/update_contractor_request_but_without_admin_only_values_when_not_admin#ContractorRequestsControllerTest (25.11s)
        "Request.count" didn't change by 1.
        Expected: 219
          Actual: 218
        test/controllers/contractor_requests_controller_test.rb:87:in `block (2 levels) in <class:ContractorRequestsControllerTest>'
        test/test_helper.rb:34:in `run_as_user'
        test/controllers/contractor_requests_controller_test.rb:86:in `block in <class:ContractorRequestsControllerTest>'
```

2) It would be helpful if the Verification Steps were more detailed, especially in indicating how to set up the system so that it has archived records. Verification Steps should be written at a fairly high level detail, so that someone with only very basic knowledge of the system can perform them. For an example see, https://issues.umd.edu/browse/LIBITD-933.

**Comment by cfitz** [comment]
@dsteelma-umd  It looks like some other PRs that were accecpted caused some issues with the fixtures being used for these test and the version initializer.  
They've been corrected and should pass now.

**Comment by dsteelma-umd** [comment]
@cfitz - This pull request has two new Rubocop violations. Please correct them.

Also, what advantage is there to having the "copy" action take place in the JavaScript? I think I would have expected a "copy" action on the PersonnelRequestController, that took the id of the request being copied, and used that to populate the form. I'm not opposed to it, but since we are not really a JavaScript shop, I'm a little concerned about maintaining it in the future.

**Comment by cfitz** [comment]
@dsteelma-umd I have removed the spaces.
Not really sure what you're meaning about the not using JS but if you want to write something up that's fine.

**Comment by dsteelma-umd** [comment]
Regarding my JavaScript comment, what I'm asking about is why do we need the "Spawner" JavaScript class? It seems to be used to round up all the fields in the displayed request, and pass it to the "new_polymorphic_url" when the "Copy" button is clicked. It requires that we add a "class: 'copy'" to all the fields that are copied in the request, as well as have a "spawned" field.

I am concerned about this because:

1) JavaScript is not one of our strengths as an organization.

2) It places control of what is getting copied from the old record to the new record in the view (based on which fields have a "copy" CSS class), which is surprising to me. For example, if we decided we didn't want to copy the "Justification" field, we'd have to change the views. I would have expected such a change to be in either the controller or the model.

3) I don't see any advantage to using JavaScript vs. having a "copy" action in controller that takes the existing request, and generates a new copy from it. Using a controller would:

a) Avoid the need for the "Spawner" JavaScript.

b) Place control of what gets copied into the controller. If we wanted, we could even move the "copy" action into the model.

4) Using JavaScript seems to make this functionality harder to write unit tests for. I notice there are no unit or integration tests for this functionality, and it seems like there should be.

I guess what I'm asking, is whether there is some overwhelming advantage to using JavaScript that outweighs the above concerns?

**Comment by cfitz** [comment]
Yes that sounds reasonable, however it is pretty minimal JS. It's just submitting a form, which allows us to mostly reuse things in already in the controller. 

Agree with the tests. I've been waiting to add selenium tests, since the ui has been moving around a lot but I added it in a recent PR. I can add tests to it there. 

But it you think we should do this another way, then make a new ticket with the requirements explicitly laid out and we can schedule it.

**Comment by dsteelma-umd** [comment]
I am okay with this solution, I was just trying to get some background on why this issue was implemented as it was.

Also, just FYI, I had to merge LIBITD-749 into this pull request again, probably because of Pull Request #120, which was merged in previously.

**Pull request merged**
